version: '3.4'

volumes:
  geth_data:
  geth_data2:
  geth_data3:
  beacon_node_data:
  beacon_node_follower_data:
  lighthouse_beacon_node_data:
  lighthouse_beacon_node_follower_data:

services:
  execution-node:
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8545:8545'
      - '30303:30303'
      - '30304:30303'
    environment:
      GETH_VERBOSITY: 5
    volumes:
      - 'geth_data:/db'
      - type: bind
        source: ./geth/geth-genesis.json
        target: /genesis.json

  execution-node-2:
    depends_on:
      - execution-node
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    environment:
      PEER: execution-node:30303
      GETH_VERBOSITY: 5
    ports:
      - '8546:8545'
      - '30305:30305'
      - '30306:30304'
    volumes:
      - 'geth_data2:/db'
      - type: bind
        source: ./geth/geth-genesis.json
        target: /genesis.json

  prysm-beacon-node:
    depends_on:
      - execution-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint:
      ['run_beacon_node.sh', '--min-sync-peers=0', '--bootstrap-node=']
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/prysm-priv-key
        target: /etc/prysm-priv-key

  prysm-beacon-node-follower:
    depends_on:
      - execution-node-2
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node-follower
      BEACON_NODE_RPC: http://prysm-beacon-node:3500
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '4001:4000'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./prysm/prysm-follower-priv-key
        target: /etc/prysm-priv-key

  prysm-validator-node:
    depends_on:
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --interop-num-validators=4
      --interop-start-index=0
      --force-clear-db
      --chain-config-file=/config/chain-config.yml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
    ports:
      - '7500:7500'
    volumes:
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml

  lodestar-beacon-node:
    depends_on:
      - execution-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      PROCESS_NAME: lodestar-beacon-node
    entrypoint: ['run_beacon_node.sh']
    ports:
      - '3500:3500'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh

  lodestar-beacon-node-follower:
    depends_on:
      - execution-node-2
      - lodestar-beacon-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      BEACON_NODE_RPC: http://lodestar-beacon-node:3500
      PROCESS_NAME: lodestar-beacon-node-follower
      VERBOSITY: debug
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lodestar/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh

  lighthouse-beacon-node:
    depends_on:
      - execution-node
    image: seananderson33/lighthouse:eip4844
    environment:
      EXECUTION_NODE_URL: "http://proxy:8551"
      VERBOSITY: debug
      TESTNET_DIR: /config
      GENERATE_GENESIS: true
    entrypoint: ["run_beacon_node.sh"]
    ports:
      - "5052:5052"
      - "9000:9000"
    volumes:
      - "lighthouse_beacon_node_data:/chaindata"
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/config.yaml
      - type: bind
        source: ./lighthouse/deploy_block.txt
        target: /config/deploy_block.txt
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt

  lighthouse-beacon-node-follower:
    depends_on:
      - execution-node-2
      - lighthouse-beacon-node
    image: seananderson33/lighthouse:eip4844
    environment:
      BEACON_NODE_RPC: http://lighthouse-beacon-node:5052
      EXECUTION_NODE_URL: "http://proxy-2:8552"
      VERBOSITY: debug
      TESTNET_DIR: /config
      GENERATE_GENESIS: false
    entrypoint: ["run_beacon_node_peer.sh"]
    ports:
      - "5053:5052"
      - "9001:9000"
    volumes:
      - "lighthouse_beacon_node_follower_data:/chaindata"
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/config.yaml
      - type: bind
        source: ./lighthouse/deploy_block.txt
        target: /config/deploy_block.txt
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lighthouse/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt

  lighthouse-validator-node:
    depends_on:
      - lighthouse-beacon-node-follower
      - lighthouse-beacon-node
    image: seananderson33/lighthouse:eip4844
    command: >
      lighthouse 
      	vc 
      	--datadir /chaindata 
      	--testnet-dir /config 
      	--init-slashing-protection 
      	--beacon-nodes http://lighthouse-beacon-node-follower:5052
    volumes:
      - "lighthouse_beacon_node_data:/chaindata"
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/config.yaml
      - type: bind
        source: ./lighthouse/deploy_block.txt
        target: /config/deploy_block.txt

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'

  proxy:
    image: ethdreamer/json_rpc_snoop:latest
    entrypoint: >
      /bin/bash -c "
        ./json_rpc_snoop -p 8551 -b 0.0.0.0 http://execution-node:8545
      "
    expose:
      - 8551

  proxy-2:
    depends_on:
      - execution-node-2
    image: ethdreamer/json_rpc_snoop:latest
    entrypoint: >
      /bin/bash -c "
        ./json_rpc_snoop -p 8552 -b 0.0.0.0 http://execution-node-2:8545
      "
    expose:
      - 8552