version: '3.4'

volumes:
  config:
  data:
  geth_data:
  geth_data2:
  beacon_node_data:
  beacon_node_follower_data:

services:
  genesis-generator:
    image: ethpandaops/ethereum-genesis-generator:latest
    entrypoint: ''
    env_file:
      - ./config/values.env
    command: bash -c 'cd /data && /usr/local/bin/eth2-val-tools keystores --source-min 0 --source-max $(($$NUMBER_OF_VALIDATORS - 1)) --source-mnemonic "$$EL_AND_CL_MNEMONIC" && /work/entrypoint.sh all'
    ports:
      - '8000:8000'
    volumes:
      - 'data:/data'
      - 'config:/config'
      - type: bind
        source: ./config/values.env
        target: /config/values.env

  execution-node:
    depends_on:
      - genesis-generator
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8545:8545'
    environment:
      GENESIS_FILE_PATH: /data/custom_config_data/genesis.json
      GETH_VERBOSITY: 4
    volumes:
      - 'geth_data:/db'
      - 'data:/data'

  execution-node-2:
    depends_on:
      - genesis-generator
      - execution-node
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    environment:
      GENESIS_FILE_PATH: /data/custom_config_data/genesis.json
      PEER: execution-node:30303
      GETH_VERBOSITY: 4
    ports:
      - '8546:8545'
    volumes:
      - 'geth_data2:/db'
      - 'data:/data'

  prysm-beacon-node:
    depends_on:
      - genesis-generator
      - execution-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint:
      ['run_beacon_node.sh', '--min-sync-peers=0', '--bootstrap-node=']
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/prysm-priv-key
        target: /etc/prysm-priv-key

  prysm-beacon-node-follower:
    depends_on:
      - genesis-generator
      - execution-node-2
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node-follower
      BEACON_NODE_RPC: http://prysm-beacon-node:3500
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '4001:4000'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./prysm/prysm-follower-priv-key
        target: /etc/prysm-priv-key

  prysm-validator-node:
    depends_on:
      - genesis-generator
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --interop-num-validators=4
      --interop-start-index=0
      --force-clear-db
      --chain-config-file=/config/chain-config.yml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
    ports:
      - '7500:7500'
    volumes:
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml

  lodestar-beacon-node:
    depends_on:
      - genesis-generator
      - execution-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      PROCESS_NAME: lodestar-beacon-node
    entrypoint: ['run_beacon_node.sh']
    ports:
      - '3500:3500'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh

  lodestar-beacon-node-follower:
    depends_on:
      - genesis-generator
      - execution-node-2
      - lodestar-beacon-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      BEACON_NODE_RPC: http://lodestar-beacon-node:3500
      PROCESS_NAME: lodestar-beacon-node-follower
      VERBOSITY: debug
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lodestar/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh

  lighthouse-beacon-node:
    depends_on:
      - genesis-generator
      - execution-node
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    environment:
      EXECUTION_NODE_URL: "http://execution-node:8551"
      VERBOSITY: trace
      TESTNET_DIR: /data
    entrypoint: ["run_beacon_node.sh"]
    ports:
      - "5052:5052"
      - "9000:9000"
    volumes:
      - "beacon_node_data:/chaindata"
      - 'data:/data'
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./data/trusted_setup.txt
        target: /data/trusted_setup.txt

  lighthouse-beacon-node-follower:
    image: lighthouse-interop
    depends_on:
      - genesis-generator
      - execution-node-2
      - lighthouse-beacon-node
    environment:
      BEACON_NODE_RPC: http://lighthouse-beacon-node:5052
      EXECUTION_NODE_URL: "http://execution-node-2:8551"
      VERBOSITY: debug
      TESTNET_DIR: /data
    entrypoint: ["run_beacon_node_peer.sh"]
    ports:
      - "5053:5052"
      - "9001:9000"
    volumes:
      - "beacon_node_follower_data:/chaindata"
      - 'data:/data'
      - type: bind
        source: ./lighthouse/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./data/trusted_setup.txt
        target: /data/trusted_setup.txt

  lighthouse-validator-node:
    image: lighthouse-interop
    depends_on:
      - genesis-generator
      - lighthouse-beacon-node-follower
      - lighthouse-beacon-node
    entrypoint: ["run_validator_node.sh"]
    volumes:
      - 'data:/data'
      - type: bind
        source: ./lighthouse/run_validator_node.sh
        target: /usr/local/bin/run_validator_node.sh

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
